// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc8qXPZPm27RTM7xgsSRLNeeltNzU5qfg',
    appId: '1:120748976198:web:989332a7f7aa58c0764247',
    messagingSenderId: '120748976198',
    projectId: 'my-phc-helper-shravan',
    authDomain: 'my-phc-helper-shravan.firebaseapp.com',
    storageBucket: 'my-phc-helper-shravan.firebasestorage.app',
    measurementId: 'G-9FSPZS7G5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzN41qLHOGjiRq0XJiJvg82LwjEzYvrC4',
    appId: '1:120748976198:android:2f782f725bc90960764247',
    messagingSenderId: '120748976198',
    projectId: 'my-phc-helper-shravan',
    storageBucket: 'my-phc-helper-shravan.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCc8qXPZPm27RTM7xgsSRLNeeltNzU5qfg',
    appId: '1:120748976198:web:ef1f5125d3bc7d83764247',
    messagingSenderId: '120748976198',
    projectId: 'my-phc-helper-shravan',
    authDomain: 'my-phc-helper-shravan.firebaseapp.com',
    storageBucket: 'my-phc-helper-shravan.firebasestorage.app',
    measurementId: 'G-SWZ6HFWER1',
  );

}